# Site settings
title: Репозиторий дополнений KODI
email: vl.maksime@gmail.com
description: vl.maksime Add-on repository
baseurl: "/repository.vlmaksime"
url: "https://vlmaksime.github.io"
github_username:  vlmaksime

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Блог
    link: https://vlmaksime.github.io/
  option2:
    name: Репозиторий дополнений KODI
    link: https://vlmaksime.github.io/repository.vlmaksime/

disqus: false

# Collections
collections:
  addons:
    output: true

# Build settings
markdown: kramdown
remote_theme: "vlmaksime/jekyll-mdl"
plugins:
  - jekyll-feed

exclude:
  - sources/